<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	  <TargetFramework>net6.0</TargetFramework>
	  <LangVersion>latest</LangVersion>
	  <ImplicitUsings>enable</ImplicitUsings>
	  <Nullable>enable</Nullable>
	  <PackageId>Beeq.Mapper</PackageId>
	  <Version>1.0.0</Version>
	  <Authors>BeeQ</Authors>
	  <Description>Mapeador de objetos automático customizable con soporte para múltiples frameworks</Description>
	  <RepositoryUrl>https://github.com/Conntinnum/BeeQ.Mapper</RepositoryUrl>
	  <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
	  <PackageReadmeFile>README.md</PackageReadmeFile>
	  <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
  </PropertyGroup>

  <ItemGroup>
    <None Include="README.md" Pack="true" PackagePath="" />
  </ItemGroup>
</Project>
